[package]
name = "heartbeat-rs"
version = "0.0.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.0", features = ["blocking"] }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
